services:
   db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rifa
      POSTGRES_USER: rifa
      POSTGRES_DB: rifa
    ports:
      - "5432:5432"

   